export const externalPosts = [
  {
    title: "Making your web app work offline",
    date: "2017-12-07T10:00:00.000Z",
    description: "A gentle introduction to offline web development",
    url: "https://css-tricks.com/making-your-web-app-work-offline-part-1/",
  },
  {
    title: "Svelte for the Experienced React Dev",
    date: "2021-05-21T10:00:00.000Z",
    description: "A high-level introduction to Svelte, from the perspective of an experienced React developer",
    url: "https://css-tricks.com/svelte-and-spring-animations/",
  },
  {
    title: "Coordinating Svelte Animations With XState",
    date: "2021-04-07T10:00:00.000Z",
    description: "An introduction to XState, for simplifying Svelte animation code",
    url: "https://css-tricks.com/svelte-and-spring-animations/",
  },
  {
    title: "Svelte and Spring Animations",
    date: "2021-01-08T10:00:00.000Z",
    description: "A deep dive into Svelte's spring animation features",
    url: "https://css-tricks.com/svelte-and-spring-animations/",
  },
  {
    title: "Integrating TypeScript with Svelte",
    date: "2020-12-28T10:00:00.000Z",
    description: "Manually adding TypeScript to a non-greenfield Svelte project",
    slug: "https://css-tricks.com/integrating-typescript-with-svelte/",
  },
  {
    title: "Pre-Caching Images with React Suspense",
    date: "2020-09-21T10:00:00.000Z",
    description: "Using Suspense to block a component's rendering until its images have loaded",
    slug: "https://css-tricks.com/pre-caching-image-with-react-suspense/",
  },
  {
    title: "How to Use CSS Grid for Sticky Headers and Footers",
    date: "2020-09-14T10:00:00.000Z",
    description: "A beginner friendly introduction to CSS Grid, with examples implementing sticky headers and footers",
    url: "https://css-tricks.com/how-to-use-css-grid-for-sticky-headers-and-footers/",
  },
  {
    title: "Making Sense of react-spring",
    date: "2020-08-20T10:00:00.000Z",
    description: "Understanding how react-spring works, and how to leverage it for common animation use cases",
    url: "https://css-tricks.com/making-sense-of-react-spring/",
  },
  {
    title: "Building Your First Serverless Service With AWS Lambda Functions",
    date: "2020-05-29T10:00:00.000Z",
    description: "A beginners introduction to the Serverless framework",
    url: "https://css-tricks.com/building-your-first-serverless-service-with-aws-lambda-functions/",
  },
  {
    title: "React Suspense in Practice",
    date: "2020-03-19T10:00:00.000Z",
    description: "A practical, hands-on tutorial to React Suspense",
    url: "https://css-tricks.com/react-suspense-in-practice/",
  },
  {
    title: "Demystifying TypeScript Discriminated Unions",
    date: "2022-01-27T10:00:00.000Z",
    description: "Explaining TypeScript unions, and discriminated unions",
    url: "https://css-tricks.com/typescript-discriminated-unions/",
  },
  {
    title: "Making a Site Work Offline Using the VitePWA Plugin",
    date: "2022-01-18T10:00:00.000Z",
    description: "Diving deeper into Vite, and using the VitePWA plugin to improve your site's performance",
    url: "https://css-tricks.com/vitepwa-plugin-offline-service-worker/",
  },
  {
    title: "Adding Vite to Your Existing Web App",
    date: "2022-01-11T10:00:00.000Z",
    description: "A fun, painless introduction to Vite",
    url: "https://css-tricks.com/adding-vite-to-your-existing-web-app/",
  },
  {
    title: "React Suspense: Lessons Learned While Loading Data",
    date: "2021-11-09T10:00:00.000Z",
    description: "A deeper dive into data loading with Suspense",
    url: "https://css-tricks.com/react-suspense-lessons-learned-while-loading-data/",
  },
];
